service: langchain-chatbot

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  timeout: 60 # Increase the timeout to 60 seconds
  stage: dev # Explicitly define the stage

functions:
  chatbot:
    handler: dist/handler.handler
    events:
      - http:
          path: chatbot
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: skippyts.doctorew.com
    stage: ${opt:stage, self:provider.stage} # Reference the provider's stage value
    basePath: ""
    certificateName: "*.doctorew.com"
    createRoute53Record: true
