service: langchain-chatbot

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  timeout: 60
  stage: dev

functions:
  chatbot:
    handler: dist/src/handler.handler
    events:
      - http:
          path: chatbot
          method: post
          cors: true # <-- CORS!
  translation:
    handler: dist/src/handler.handler
    events:
      - http:
          path: translation
          method: post
          cors: true # <-- CORS!
  personalAssistant:
    handler: dist/src/handler.handler
    events:
      - http:
          path: personalAssistant
          method: post
  sentimentAnalysis:
    handler: dist/src/handler.handler
    events:
      - http:
          path: sentimentAnalysis
          method: post
          cors: true # <-- CORS!
  foxtrot:
    handler: dist/src/handler.handler
    events:
      - http:
          path: foxtrot
          method: post
          cors: true # <-- CORS!

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: skippyts.doctorew.com
    stage: ${opt:stage, self:provider.stage}
    basePath: ""
    certificateName: "*.doctorew.com"
    createRoute53Record: true
